#!/bin/bash
# Test script for color emoji and Unicode symbol rendering

echo "═══════════════════════════════════════════"
echo "         COLOR EMOJI & ICONS TEST          "
echo "═══════════════════════════════════════════"
echo ""

echo "── Common Emoji ──────────────────────────"
echo "  Faces:    😀 😃 😄 😁 😆 😅 🤣 😂"
echo "  More:     🥹 😊 😇 🙂 😉 😌 😍 🥰"
echo "  Cool:     😎 🤩 🥳 😏 😒 😞 😔 😟"
echo "  Angry:    😤 😠 😡 🤬 🤯 😳 🥵 🥶"
echo "  Silly:    🤪 😜 😝 😛 🤑 🤗 🤭 🫢"
echo "  Sick:     🤮 🤧 😷 🤒 🤕 🥴 😵 🤐"
echo ""

echo "── Skin Tone Modifiers ───────────────────"
echo "  Wave:     👋 👋🏻 👋🏼 👋🏽 👋🏾 👋🏿"
echo "  Thumb:    👍 👍🏻 👍🏼 👍🏽 👍🏾 👍🏿"
echo ""

echo "── Animals ─────────────────────────────── "
echo "  🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐨 🐯"
echo "  🦁 🐮 🐷 🐸 🐵 🐔 🐧 🐦 🦅 🦆"
echo "  🦋 🐛 🐝 🐞 🦗 🕷️ 🦂 🐢 🐍 🦎"
echo ""

echo "── Food & Drink ─────────────────────────"
echo "  🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍒"
echo "  🍕 🍔 🌭 🌮 🌯 🍟 🍿 🧀 🥚 🍳"
echo "  🍺 🍻 🥂 🍷 🍸 🍹 🍾 ☕ 🍵 🧃"
echo ""

echo "── Travel & Weather ──────────────────────"
echo "  🚗 🚕 🚙 🚌 🚎 🏎️ 🚓 🚑 🚒 🚐"
echo "  ✈️ 🚀 🛸 🚁 🛶 ⛵ 🚢 🛥️ 🚂 🚆"
echo "  ☀️ 🌤️ ⛅ 🌥️ ☁️ 🌦️ 🌧️ ⛈️ 🌩️ 🌨️"
echo ""

echo "── Flags ─────────────────────────────────"
echo "  🇺🇸 🇬🇧 🇩🇪 🇫🇷 🇯🇵 🇨🇳 🇧🇷 🇮🇳 🇦🇹 🇪🇺"
echo ""

echo "── Objects & Symbols ─────────────────────"
echo "  💻 🖥️ 🖨️ ⌨️ 🖱️ 📱 📞 📺 📷 💡"
echo "  🔑 🔒 🔓 🛡️ ⚙️ 🔧 🔨 ⚡ 🔥 💧"
echo "  ❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔"
echo "  ⭐ 🌟 ✨ 💫 🎵 🎶 🎯 🎲 🎮 🕹️"
echo ""

echo "── Hands & Gestures ─────────────────────"
echo "  👍 👎 👊 ✊ 🤛 🤜 🤞 ✌️ 🤟 🤘"
echo "  👌 🤌 🤏 👈 👉 👆 👇 ☝️ ✋ 🤚"
echo "  🫶 🙏 🤝 💪 🫰 🫱 🫲 🫳 🫴 🫵"
echo ""

echo "── Text Presentation vs Emoji ────────────"
echo "  These should render as emoji (VS16):"
echo "    ☺️ ☹️ ☠️ ❤️ ♻️ ⚠️ ✅ ❌ ⬆️ ⬇️"
echo ""
echo "  These should render as text symbols:"
echo "    ☺ ☹ ☠ ♻ ⚠ ✓ ✗ ↑ ↓ → ←"
echo ""

echo "── Emoji in Context ──────────────────────"
echo "  Status:  ✅ Build passed    ❌ Tests failed"
echo "  Git:     🔀 Merge branch    📝 Edit file"
echo "  Alert:   ⚠️  Warning         🔴 Error"
echo "  Rating:  ⭐⭐⭐⭐⭐  (5/5)"
echo "  Loading: 🔄 Please wait..."
echo "  Done:    🎉 All tests passed!"
echo ""

echo "── Emoji Mixed with ASCII ────────────────"
echo "  Hello 👋 World 🌍!"
echo "  I ❤️  terminal emulators"
echo "  Coffee ☕ + Code 💻 = 🚀"
echo "  Bug 🐛 → Fix 🔧 → Ship 🚢"
echo ""

echo "── Size & Alignment Test ─────────────────"
echo "  aaa🎉bbb  (emoji between ASCII)"
echo "  🎉🎉🎉🎉🎉  (consecutive emoji)"
echo "  a🎉b🎉c🎉d  (alternating)"
echo "  ├── 📁 src"
echo "  │   ├── 📄 main.zig"
echo "  │   └── 📁 font"
echo "  └── 📄 build.zig"
echo ""

echo "═══════════════════════════════════════════"
echo "              TEST COMPLETE                "
echo "═══════════════════════════════════════════"
